<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s</string>
		<string>S</string>
		<string>asm</string>
		<string>ASM</string>
	</array>
	<key>name</key>
	<string>ASM</string>
	<key>scopeName</key>
	<string>source.asm</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(;).*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.asm</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.asm</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.asm</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9]+|0x[0-9A-Za-z]+|[0-9A-Za-z]+h|[01]+b)\b</string>
			<key>name</key>
			<string>constant.numeric.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([qd]?word|byte)\b</string>
			<key>name</key>
			<string>storage.type.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"[^"]*"|'[^']*'</string>
			<key>name</key>
			<string>string.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>section</string>
			<key>name</key>
			<string>storage.section.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.?(global|extern|section)</string>
			<key>name</key>
			<string>storage.type.function.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[a-zA-Z0-9_]+:?$</string>
			<key>name</key>
			<string>entity.name.function.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s+[a-zA-Z0-9_]+</string>
			<key>name</key>
			<string>support.function.instruction.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.[a-zA-Z0-9_]+:?</string>
			<key>name</key>
			<string>keyword.label.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(db|equ|times|rel)\b</string>
			<key>name</key>
			<string>keyword.control.asm</string>
		</dict>
	</array>
</dict>
</plist>
